services:
  orgarif-web:
    build: orgarif-web
    ports:
      - "8081:8080"
    links:
      - psql
  psql:
    image: postgres:13.1
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_DB=orgarif
      - POSTGRES_USER=orgarif
      - POSTGRES_PASSWORD=orgarif-test-password
    volumes:
      - ./psql/initiate-database.sql:/docker-entrypoint-initdb.d/init.sql